<?php
/**
 * @file
 * Install, update and uninstall functions for the standard install profile.
 */

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 */
function tommidep_install() {
  include_once DRUPAL_ROOT . '/profiles/standard/standard.install';
  standard_install();

  //Default themes
  theme_enable(array('tommi'));
  variable_set('theme_default','tommi');
}
